apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-sc
provisioner: kubernetes.io/no-provisioner
parameters:
  type: pd-standard
reclaimPolicy: Retain
volumeBindingMode: Immediate
