apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-deployment-claim
  namespace: tasks

spec:
  storageClassName: "minio-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
